package com.kc3981.helloworld;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
    	
    	String testingUsedVar;
    	
    	
        return true;
    }
}
